      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: pandapolarb3ar/orders-gitops
          token: ${{ secrets.GITOPS_PAT_SECRET }}
          path: gitops

      - name: Update image tag in GitOps repo
        run: |
          sed -i \
            "s|image: ghcr.io/pandapolarb3ar/orders-api:.*|image: ghcr.io/pandapolarb3ar/orders-api:${GITHUB_SHA}|" \
            gitops/deployment.yaml

      - name: Commit and push GitOps change
        run: |
          cd gitops

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add deployment.yaml

          git diff --cached --quiet && exit 0

          git commit -m "Deploy orders-api ${GITHUB_SHA}"
          git push
